url: "https://www.astrolojiyolcusu.com"

title: "Astroloji Yolcusu"
description: "Astroloji ve Esmalarla Şifa"

email_address: astrolojiyolcusu@gmail.com
facebook_page: https://facebook.com/zeynepbaharoffical
youtube_page: https://youtube.com/astrolojiyolculuguakademisi

image: /assets/img/cover/960797.jpg

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      class: post-template

str_about: Hakkında
str_services: Hizmetler
str_not_found: Sayfa bulunamadı

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

