title: "Astroloji Yolculuğu Akademisi"
description: "Astroloji ve Esmalarla Şifa"
email_address: info@astrolojiyolculugu.com
facebook_page: https://facebook.com/astrolojiyolculugu
instagram_page: https://instagram.com/astrolojiyolculugu
youtube_page: https://youtube.com/astrolojiyolculuguakademisi
sass:
  style: compressed
