url: "https://www.astrolojiyolcusu.com"

title: "Astroloji Yolcusu"
description: "Astroloji ve Esmalarla Şifa"

theme_settings:
  footer_text: "Yükseklere ulaşmak, yıldızların ruhunuzda saklı
  kalmasıdır. Derinleri hayal edin, her rüya için hedef önünüze gelir.
  &nbsp;<em><small>Ralph Vaull Starr</small></em>"
  email_address: astrolojiyolcusu@gmail.com
  facebook: astrolojiyolculugu
  flickr:
  google_plus:
  instagram:
  linkedin:
  pinterest:
  reddit:
  tumblr:
  twitter:
  vimeo:
  youtube: UChqfxzORYlvMezSVmQfo3IQ
  
  str_next_post: "SONRAKİ GÖNDERİ"
  str_previous_post: "ÖNCEKİ GÖNDERİ"
  str_next_page: "İleri"
  str_previous_page: "Geri"

paginate: 5
paginate_path: ":num"

markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
