url: "https://www.astrolojiyolcusu.com"

title: "Astroloji Yolculuğu Akademisi"
description: "Astroloji ve Esmalarla Şifa"

email_address: astrolojiyolcusu@gmail.com
facebook_page: https://facebook.com/zeynepbaharoffical
instagram_page: https://instagram.com/astrolojiyolculugu
youtube_page: https://youtube.com/astrolojiyolculuguakademisi

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      class: post-template

sass:
  style: compressed

str_about: Hakkında

plugins:
  - jekyll-seo-tag
